// Mocks generated by Mockito 5.4.6 from annotations
// in inner_garden/test/album_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_image_compress/flutter_image_compress.dart' as _i4;
import 'package:inner_garden/services/photo_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PhotoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoService extends _i1.Mock implements _i2.PhotoService {
  MockPhotoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> uploadStudentPhoto({
    required _i4.XFile? photoFile,
    required String? studentId,
    required String? date,
    required String? teacherId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadStudentPhoto, [], {
              #photoFile: photoFile,
              #studentId: studentId,
              #date: date,
              #teacherId: teacherId,
            }),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#uploadStudentPhoto, [], {
                  #photoFile: photoFile,
                  #studentId: studentId,
                  #date: date,
                  #teacherId: teacherId,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> deletePhoto({
    required String? photoUrl,
    required String? studentId,
    required String? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deletePhoto, [], {
              #photoUrl: photoUrl,
              #studentId: studentId,
              #date: date,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<Map<String, List<Map<String, dynamic>>>> getPhotosByDateStream({
    required String? studentId,
    required int? daysBack,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPhotosByDateStream, [], {
              #studentId: studentId,
              #daysBack: daysBack,
            }),
            returnValue:
                _i3.Stream<Map<String, List<Map<String, dynamic>>>>.empty(),
          )
          as _i3.Stream<Map<String, List<Map<String, dynamic>>>>);

  @override
  _i3.Future<void> deleteOldPhotos({
    required String? studentId,
    required int? daysToKeep,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldPhotos, [], {
              #studentId: studentId,
              #daysToKeep: daysToKeep,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
