// Mocks generated by Mockito 5.4.6 from annotations
// in inner_garden/test/viewmodels/super_admin_dashboard_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:inner_garden/models/school_member_model.dart' as _i7;
import 'package:inner_garden/models/school_model.dart' as _i6;
import 'package:inner_garden/repositories/platform_repository.dart' as _i2;
import 'package:inner_garden/services/super_admin_service.dart' as _i4;
import 'package:inner_garden/services/tenant_functions_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlatformStats_0 extends _i1.SmartFake implements _i2.PlatformStats {
  _FakePlatformStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInvitationResult_1 extends _i1.SmartFake
    implements _i3.InvitationResult {
  _FakeInvitationResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAcceptInvitationResult_2 extends _i1.SmartFake
    implements _i3.AcceptInvitationResult {
  _FakeAcceptInvitationResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateSchoolResult_3 extends _i1.SmartFake
    implements _i3.CreateSchoolResult {
  _FakeCreateSchoolResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SuperAdminService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuperAdminService extends _i1.Mock implements _i4.SuperAdminService {
  MockSuperAdminService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<bool> get superAdminStream =>
      (super.noSuchMethod(
            Invocation.getter(#superAdminStream),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Future<bool> isSuperAdmin() =>
      (super.noSuchMethod(
            Invocation.method(#isSuperAdmin, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [PlatformRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformRepository extends _i1.Mock
    implements _i2.PlatformRepository {
  MockPlatformRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i6.SchoolModel>> getSchoolsStream() =>
      (super.noSuchMethod(
            Invocation.method(#getSchoolsStream, []),
            returnValue: _i5.Stream<List<_i6.SchoolModel>>.empty(),
          )
          as _i5.Stream<List<_i6.SchoolModel>>);

  @override
  _i5.Future<_i6.SchoolModel?> getSchoolById(String? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#getSchoolById, [schoolId]),
            returnValue: _i5.Future<_i6.SchoolModel?>.value(),
          )
          as _i5.Future<_i6.SchoolModel?>);

  @override
  _i5.Future<int> getSchoolCount() =>
      (super.noSuchMethod(
            Invocation.method(#getSchoolCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getMemberCount(String? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#getMemberCount, [schoolId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getStudentCount(String? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentCount, [schoolId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> updateSchoolSubscription(String? schoolId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateSchoolSubscription, [schoolId, status]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSchool(String? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSchool, [schoolId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> permanentlyDeleteSchool(String? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#permanentlyDeleteSchool, [schoolId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.PlatformStats> getPlatformStats() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatformStats, []),
            returnValue: _i5.Future<_i2.PlatformStats>.value(
              _FakePlatformStats_0(
                this,
                Invocation.method(#getPlatformStats, []),
              ),
            ),
          )
          as _i5.Future<_i2.PlatformStats>);
}

/// A class which mocks [TenantFunctionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTenantFunctionsService extends _i1.Mock
    implements _i3.TenantFunctionsService {
  MockTenantFunctionsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.InvitationResult> createInvitation({
    required String? email,
    required _i7.MemberRole? role,
    required String? schoolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInvitation, [], {
              #email: email,
              #role: role,
              #schoolId: schoolId,
            }),
            returnValue: _i5.Future<_i3.InvitationResult>.value(
              _FakeInvitationResult_1(
                this,
                Invocation.method(#createInvitation, [], {
                  #email: email,
                  #role: role,
                  #schoolId: schoolId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.InvitationResult>);

  @override
  _i5.Future<_i3.AcceptInvitationResult> acceptInvitation({
    required String? token,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptInvitation, [], {
              #token: token,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i5.Future<_i3.AcceptInvitationResult>.value(
              _FakeAcceptInvitationResult_2(
                this,
                Invocation.method(#acceptInvitation, [], {
                  #token: token,
                  #password: password,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AcceptInvitationResult>);

  @override
  _i5.Future<_i3.CreateSchoolResult> createSchool({
    required String? name,
    required String? adminEmail,
    Map<String, dynamic>? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSchool, [], {
              #name: name,
              #adminEmail: adminEmail,
              #config: config,
            }),
            returnValue: _i5.Future<_i3.CreateSchoolResult>.value(
              _FakeCreateSchoolResult_3(
                this,
                Invocation.method(#createSchool, [], {
                  #name: name,
                  #adminEmail: adminEmail,
                  #config: config,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.CreateSchoolResult>);
}
